= Getting started

Angela provides a Java API to handle a Terracotta cluster lifecycle.
It also provides a set of utility methods to help with testing (e.g. network controlling for HA testing)

It can set up a TSA from :

 - a Kit tarball
 - the SAG installer
 - a local build

It can install the cluster locally or remotely

It can execute functions that contain client code locally or remotely

== Initial setup

For running tests on a node angela expects a directory at `/data/angela` to store all its metadata.
So make sure that this directory exists or can be created before running any tests.
For more details on what what that directory is used for, refer to <<directory-structure.adoc#, Angela Directory Structure>>

== Tsa Cluster example

Given the following cluster configuration:

[source,xml]
----
include::../resources/tc-config-a.xml[tags=servers]
----

We expect the TSA to contain one Terracotta server running on localhost, and this will be automatically resolved by Angela.
We can ask now Angela to setup such a cluster:

[source,java]
----
include::../java/GettingStarted.java[tags=configureCluster]
----
<1> Create a custom configuration context that is going to hold all the configurable bits
<2> Define the TSA config
<3> Specify the Terracotta cluster topology
<4> Specify the Terracotta distribution : version, package type (KIT) and License
<5> Specify the Terracotta cluster config
<6> Specify the license in case the distribution is enterprise
<7> Create a Tsa logical instance that serves as an endpoint to call functionalities regarding the Tsa lifecycle
<8> Install the Tsa from the distribution on the appropriate server(s) (localhost in this case)
<9> Start all servers from the Tsa
<10> Install the license with the cluster tool
<11> Stop all Terracotta servers and cleans up the installation

== Tsa API

[source,java]
----
include::../java/GettingStarted.java[tags=showTsaApi]
----
<1> Install all Terracotta servers for the given topology
<2> Start all Terracotta servers
<3> License all Terracotta servers
<4> Get the reference of the active server. Null is returned if there is none. An exception is throw if there are more than one
<5> Get the references of all active servers. Get an empty collection if there are none.
<6> Get the reference of the passive server. Null is returned if there is none. An exception is throw if there are more than one
<7> Get the references of all passive servers. Get an empty collection if there are none.
<8> Stop all Terracotta servers
<9> Start one Terracotta server
<10> Stop one Terracotta server
<11> Get the current state of the Terracotta server

== Client array example

[source,java]
----
include::../java/GettingStarted.java[tags=runClient]
----
<1> Define the client array config
<2> Specify the license that the TC clients will use
<3> Define the client array topology
<4> Specify the distribution from which to install the client jars
<5> Specify the list of hosts that are going to be used by this client array (two clients, both on localhost in this case)
<6> Create a client array on the remote servers
<7> Execute the lambda on all the remote clients
<8> Wait until all the clients finish their execution
